#include <bits/stdc++.h>
using namespace std;


using i64 = long long;
using u64 = unsigned long long;
using u32 = unsigned;
using u128 = unsigned __int128;

#define endl '\n'

//超级板子（无 std前缀 ， endl = '\n' , 但是用真正endl可加std::）


struct node{
	int val = 0;
	int cst = 0;
	double z = cst/val;
}arr[10010];

void solve(){}

signed main (){
	std::ios::sync_with_stdio(false);std::cin.tie(0);
	

	return 0;
}